<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="59" started-at="2017-09-18T08:19:00Z" finished-at="2017-09-18T08:19:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="59" started-at="2017-09-18T08:19:00Z" finished-at="2017-09-18T08:19:00Z">
      <class name="actiTime.NewTest123">
        <test-method status="FAIL" signature="test1()[pri:0, instance:actiTime.NewTest123@4520ebad]" name="test1" is-config="true" duration-ms="0" started-at="2017-09-18T13:49:00Z" finished-at="2017-09-18T13:49:00Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at actiTime.NewTest123.test1(NewTest123.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="SKIP" signature="f()[pri:1, instance:actiTime.NewTest123@4520ebad]" name="f" duration-ms="7" started-at="2017-09-18T13:49:00Z" finished-at="2017-09-18T13:49:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="SKIP" signature="g()[pri:2, instance:actiTime.NewTest123@4520ebad]" name="g" duration-ms="4" started-at="2017-09-18T13:49:00Z" finished-at="2017-09-18T13:49:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- g -->
      </class> <!-- actiTime.NewTest123 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
